### ISSUE TITLE
请问该项目优化了哪些方面？

### ISSUE THREAD

**Issue by pansong291** [handsomezhou/Pinyin4j#1]
你好，请问这个项目与原Pinyin4j相比，哪些方面更为有优势，或者说简化了哪部分？

[TinyPinyin](https://github.com/promeG/TinyPinyin)这个项目与原Pinyin4j相比，前者清楚地将不同之处阐述了出来。请问能不能在内存和速度方面，像TinyPinyin一样做一些优化呢？

**Comment by handsomezhou** [comment]
只是在原Pinyin4j项目上删除了一些没有用到的代码，保留了一些必要的代码。
然后将其用到了[PinyinSearch](https://github.com/handsomezhou/PinyinSearchLibrary)，[T9Search](https://github.com/handsomezhou/T9SearchLibrary)，[QwertySearch](https://github.com/handsomezhou/QwertySearchLibrary)等项目中。
